mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264

notifications:
  enabled: true
  webhook:
    url: http://127.0.0.1:8080
    events:
      - new
      - update
      - end
    labels:
      - person
      - car

cameras:
  indoor:
    ffmpeg:
      inputs:
        - path: rtsp://LadyColeen:Q231179e@10.0.0.102:554/stream2
          roles:
            - detect
        - path: rtsp://LadyColeen:Q231179e@10.0.0.102:554/stream1
          roles:
            - record

    detect:
      enabled: true
      width: 640
      height: 360

    record:
      enabled: true
      continuous:
        days: 0
      motion:
        days: 7

    snapshots:
      enabled: true

    objects:
      track:
        - person

  outdoor:
    ffmpeg:
      inputs:
        - path: rtsp://LadyColeen:Q231179e@10.0.0.104:554/stream2
          roles:
            - detect
        - path: rtsp://LadyColeen:Q231179e@10.0.0.104:554/stream1
          roles:
            - record

    detect:
      enabled: true
      width: 640
      height: 360

    record:
      enabled: true
      continuous:
        days: 0
      motion:
        days: 7

    snapshots:
      enabled: true

    objects:
      track:
        - person
        - car

detectors:
  ov:
    type: openvino
    device: GPU

version: 0.17-0
